### ISSUE TITLE
MailchimpApiUser->processBatchOperations() throws an error because it tries to access a private variable

### ISSUE THREAD

**Issue by ryanblackmore** [thinkshout/mailchimp-api-php#119]
Both Mailchimp and Mailchimp2 have batch_operations as a private attribute

If MailchimpApiUser or any class that extends that attemps to call processBatchOperations(), it chokes.

**Comment by jvandesande** [comment]
I'm running into the same issue here .

**Comment by szeidler** [comment]
Same issue here.

**Comment by Matt-B50** [comment]
Same here - please fix

**Comment by Matt-B50** [comment]
Please commit @szeidler's patch from over a year ago.

**Comment by ryanblackmore** [comment]
Via thinkshout's business contact form I've inquired if this project has been abandoned.

**Comment by bdimaggio** [comment]
I'm very sorry about this, folks — ownership of this repo passed from one set of hands to another internally over here, and we didn't know about this issue. Working on it now and will have an update within the next couple of days at most.
