### ISSUE TITLE
Complete testing of methods for products

### ISSUE THREAD

**Issue by taz77** [thinkshout/mailchimp-api-php#12]
Need to finish unit tests for all methods associated with the products.

**Comment by taz77** [comment]
I will have to wait till #7 gets finalised before making the PR to fix this issue. I have included the changes in #7 to my branch that provides the additional unit testing for products.

**Comment by ruscoe** [comment]
#7 is merged in..

**Comment by taz77** [comment]
Sweet!

**Comment by ruscoe** [comment]
Merged. Thank you!
