### ISSUE TITLE
Dynamic property creation errors in PHP 8.2

### ISSUE THREAD

**Issue by jshster** [thinkshout/mailchimp-api-php#127]
I'm using the latest version of the PHP library and when attempting to add a member to the list (and I suspect do anything!) I have the following Deprecated errors generated.   I did find the following issue which says it was fixed a year ago but these errors were generated today.  

Deprecated: Creation of dynamic property MailchimpMarketing\ApiClient::$accountExport is deprecated in \vendor\mailchimp\marketing\lib\Configuration.php on line 70

Deprecated: Creation of dynamic property MailchimpMarketing\ApiClient::$accountExports is deprecated in \vendor\mailchimp\marketing\lib\Configuration.php on line 71

Deprecated: Creation of dynamic property MailchimpMarketing\ApiClient::$activityFeed is deprecated in \vendor\mailchimp\marketing\lib\Configuration.php on line 72

Deprecated: Creation of dynamic property MailchimpMarketing\ApiClient::$authorizedApps is deprecated in \vendor\mailchimp\marketing\lib\Configuration.php on line 73

Deprecated: Creation of dynamic property MailchimpMarketing\ApiClient::$automations is deprecated in \vendor\mailchimp\marketing\lib\Configuration.php on line 74

Deprecated: Creation of dynamic property MailchimpMarketing\ApiClient::$batchWebhooks is deprecated in \vendor\mailchimp\marketing\lib\Configuration.php on line 75

Deprecated: Creation of dynamic property MailchimpMarketing\ApiClient::$batches is deprecated in \vendor\mailchimp\marketing\lib\Configuration.php on line 76

Deprecated: Creation of dynamic property MailchimpMarketing\ApiClient::$campaignFolders is deprecated in \vendor\mailchimp\marketing\lib\Configuration.php on line 77

Deprecated: Creation of dynamic property MailchimpMarketing\ApiClient::$campaigns is deprecated in \vendor\mailchimp\marketing\lib\Configuration.php on line 78

Deprecated: Creation of dynamic property MailchimpMarketing\ApiClient::$connectedSites is deprecated in \vendor\mailchimp\marketing\lib\Configuration.php on line 79

Deprecated: Creation of dynamic property MailchimpMarketing\ApiClient::$conversations is deprecated in \vendor\mailchimp\marketing\lib\Configuration.php on line 80

Deprecated: Creation of dynamic property MailchimpMarketing\ApiClient::$customerJourneys is deprecated in \vendor\mailchimp\marketing\lib\Configuration.php on line 81

Deprecated: Creation of dynamic property MailchimpMarketing\ApiClient::$ecommerce is deprecated in \vendor\mailchimp\marketing\lib\Configuration.php on line 82

Deprecated: Creation of dynamic property MailchimpMarketing\ApiClient::$facebookAds is deprecated in \vendor\mailchimp\marketing\lib\Configuration.php on line 83

Deprecated: Creation of dynamic property MailchimpMarketing\ApiClient::$fileManager is deprecated in \vendor\mailchimp\marketing\lib\Configuration.php on line 84

Deprecated: Creation of dynamic property MailchimpMarketing\ApiClient::$landingPages is deprecated in \vendor\mailchimp\marketing\lib\Configuration.php on line 85

Deprecated: Creation of dynamic property MailchimpMarketing\ApiClient::$lists is deprecated in \vendor\mailchimp\marketing\lib\Configuration.php on line 86

Deprecated: Creation of dynamic property MailchimpMarketing\ApiClient::$ping is deprecated in \vendor\mailchimp\marketing\lib\Configuration.php on line 87

Deprecated: Creation of dynamic property MailchimpMarketing\ApiClient::$reporting is deprecated in \vendor\mailchimp\marketing\lib\Configuration.php on line 88

Deprecated: Creation of dynamic property MailchimpMarketing\ApiClient::$reports is deprecated in \vendor\mailchimp\marketing\lib\Configuration.php on line 89

Deprecated: Creation of dynamic property MailchimpMarketing\ApiClient::$root is deprecated in \vendor\mailchimp\marketing\lib\Configuration.php on line 90

Deprecated: Creation of dynamic property MailchimpMarketing\ApiClient::$searchCampaigns is deprecated in \vendor\mailchimp\marketing\lib\Configuration.php on line 91

Deprecated: Creation of dynamic property MailchimpMarketing\ApiClient::$searchMembers is deprecated in \vendor\mailchimp\marketing\lib\Configuration.php on line 92

Deprecated: Creation of dynamic property MailchimpMarketing\ApiClient::$Surveys is deprecated in \vendor\mailchimp\marketing\lib\Configuration.php on line 93

Deprecated: Creation of dynamic property MailchimpMarketing\ApiClient::$templateFolders is deprecated in \vendor\mailchimp\marketing\lib\Configuration.php on line 94

Deprecated: Creation of dynamic property MailchimpMarketing\ApiClient::$templates is deprecated in \vendor\mailchimp\marketing\lib\Configuration.php on line 95

Deprecated: Creation of dynamic property MailchimpMarketing\ApiClient::$verifiedDomains is deprecated in \vendor\mailchimp\marketing\lib\Configuration.php on line 96

**Comment by aprice42** [comment]
Thanks for the flag @jshster! Can you please share the issue you are referring to where this was listed as fixed?

**Comment by jshster** [comment]
My apologies, I did mean to include that link.  Here's the link to the issue https://github.com/thinkshout/mailchimp-api-php/issues/122

**Comment by xenophyle** [comment]
Hi @jshster , it looks like these notices are coming from https://github.com/mailchimp/mailchimp-marketing-php, which we don't maintain. Does this sound right to you: are you using https://www.drupal.org/project/mailchimp_marketing?

**Comment by jshster** [comment]
Hi @xenophyle , you're absolutely right! My mistake.  I must have found your project in a search without realising it was different.  Apologies.

**Comment by xenophyle** [comment]
Great. Thank you!
