### ISSUE TITLE
Coding standards

### ISSUE THREAD

**Issue by ruscoe** [thinkshout/mailchimp-api-php#19]
- [x] Ensure function arguments match names in MailChimp API
- [x] Ensure function docs are consistently formatted
- [x] Ensure short array format is used consistently (`[]` not `array()`)

**Comment by AmyVS** [comment]
@ruscoe - I believe this issue is resolved. Please feel free to check over my work, just to be on the safe side. 😄

**Comment by ruscoe** [comment]
Looks good to me 👍
