### ISSUE TITLE
MailchimpAutomations?

### ISSUE THREAD

**Issue by a-fro** [thinkshout/mailchimp-api-php#20]
Hey team ThinkShout! Have you discussed adding support for automations to the library? 

If I were to work on a pull request and follow the same patterns/standards you've established, would you consider it? Currently, we only need support for adding subscribers to a workflow, though I could take a look at other likely automation endpoint candidates for inclusion.

Eventually, I'd be interested in helping with a mailchimp_automations Drupal submodule, though that's probably more of a commitment than I can make at this time. 

Thanks for your consideration!

**Comment by mshaver** [comment]
Hi @a-fro,

Feel free to submit a pull request with the automations piece if you'd like. We don't have any immediate plans to add that to the library at this point, but might later in the year. 

Thanks

**Comment by a-fro** [comment]
Great. Thanks @mshaver!

**Comment by a-fro** [comment]
@mshaver pr created. https://github.com/thinkshout/mailchimp-api-php/pull/21. Thanks for considering.

**Comment by ruscoe** [comment]
Thanks, @a-fro! Your pull request looks great and has been merged. Sorry for the delay in getting to this.
