### ISSUE TITLE
PHP 5.3 support?

### ISSUE THREAD

**Issue by idevit** [thinkshout/mailchimp-api-php#24]
Thank you for maintaining the mailchimp-api-php library :)

Release v1.0.3 is broken with mailchimp module for drupal 7.x-4.4
Major PHP error expecting different [ { brackets tested in php 5.3 (whom still is officially supported)

git clone from master, then composer install does work nicely still
Solution make a new release.

**Comment by Greg-Boggs** [comment]
Hi idevit,

While Drupal 7 still supports end of life PHP, this library does not because it has dependencies that do not. Moreover, you should upgrade your PHP because it's unsafe to run end of life PHP in production.
