### ISSUE TITLE
Tag a new release so that Mailchimp Ecommerce will function

### ISSUE THREAD

**Issue by taz77** [thinkshout/mailchimp-api-php#27]
We need a new release tagged. The Drupal [Mailchimp Ecommerce](https://www.drupal.org/project/mailchimp_ecommerce) module will not function without the MailchimpEcommerce class that was committed after v1.0.3.

**Comment by ruscoe** [comment]
Sorry for the late response to this.

Release: https://github.com/thinkshout/mailchimp-api-php/releases/tag/v1.0.4

Packagist: https://packagist.org/packages/thinkshout/mailchimp-api-php#1.0.4
