### ISSUE TITLE
getCampaignContent method (Patch attached)

### ISSUE THREAD

**Issue by torgospizza** [thinkshout/mailchimp-api-php#29]
Hi everyone,

Thanks so much for the awesome work getting the new API Library and Drupal module up to snuff.

I was in need of a getter to the setCampaignContent method, as we have an archive page on the site where we occasionally send users who missed an email. 

It was pretty simple to implement, so hopefully this will be an easy addition to this awesome lib.

Thanks!

Erik

[mailchimp-api_getCampaignContent.patch.txt](https://github.com/thinkshout/mailchimp-api-php/files/490828/mailchimp-api_getCampaignContent.patch.txt)

**Comment by ruscoe** [comment]
Patched in. Thank you!
