### ISSUE TITLE
Fatal error: Call to a member function getBody() on a non-object in ...Mailchimp.php on line 282

### ISSUE THREAD

**Issue by aklump** [thinkshout/mailchimp-api-php#30]
I was getting back a cURL error: cURL error 60: SSL certificate problem: unable to get local issuer certificate (see http://curl.haxx.se/libcurl/c/libcurl-errors.html), which was being caught, but because the exception had no response, the method getBody() was failing.  I've attached the patch that I used to get around this.
[bug.diff.txt](https://github.com/thinkshout/mailchimp-api-php/files/516774/bug.diff.txt)

**Comment by Greg-Boggs** [comment]
Can you send a pull request rather than attaching a patch? It makes code review an acceptance easier.

**Comment by aklump** [comment]
Sure--sorry, used to d.o.  When I cloned to make the pull request, I found that this issue has already been fixed, so I'm going to mark closed.  My bad, I thought I had the most recent version before I reported it.  Thanks for the work on this!

**Comment by Greg-Boggs** [comment]
Awesome! If you see anything else, don't hesitate to send a PR. We're always happy to work with the community.
