### ISSUE TITLE
Add more campaign report options

### ISSUE THREAD

**Issue by apmsooner** [thinkshout/mailchimp-api-php#35]
It would be helpful to have access to full range of mailchimp campaign reports. I've added my own function to the library as such:

`/**
   * Gets a specific report for a specific campaign.
   *
   * @param string $campaign_id
   *   The ID of the campaign.
   * @param string $type
   *  The type of report to generate path url
   *  - abuse-reports
   *    @see http://developer.mailchimp.com/documentation/mailchimp/reference/reports/abuse-reports
   *  - advice
   *    @see http://developer.mailchimp.com/documentation/mailchimp/reference/reports/advice
   *  - click-details
   *    @see http://developer.mailchimp.com/documentation/mailchimp/reference/reports/click-details
   *  - domain-performance
   *    @see http://developer.mailchimp.com/documentation/mailchimp/reference/reports/domain-performance
   *  - eepurl
   *    @see http://developer.mailchimp.com/documentation/mailchimp/reference/reports/eepurl
   *  - email-activity
   *    @see http://developer.mailchimp.com/documentation/mailchimp/reference/reports/email-activity
   *  - locations
   *    @see http://developer.mailchimp.com/documentation/mailchimp/reference/reports/locations
   *  - sent-to
   *    @see http://developer.mailchimp.com/documentation/mailchimp/reference/reports/sent-to
   *  - sub-reports
   *    @see http://developer.mailchimp.com/documentation/mailchimp/reference/reports/sub-reports
   *  - unsubscribed
   *    @see http://developer.mailchimp.com/documentation/mailchimp/reference/reports/unsubscribed
   * @param array $parameters
   *   Associative array of optional request parameters.
   *
   * @return object
   *
   */
  public function getCampaignReport($campaign_id, $type, $parameters = []) {
    $tokens = [
      'campaign_id' => $campaign_id,
    ];

    return $this->request('GET', '/reports/{campaign_id}/' . $type, $tokens, $parameters);
  }`

**Comment by ruscoe** [comment]
Added to the library. Thanks!
