### ISSUE TITLE
Publish library on Packagist

### ISSUE THREAD

**Issue by taz77** [thinkshout/mailchimp-api-php#4]
Would it be possible for you guys to publish this library on Packagist so it can be included via Composer? I run my Drupal site dependencies via Composer and Drupal Composer Manager module, just makes life easy.

**Comment by ruscoe** [comment]
Published here: https://packagist.org/packages/thinkshout/mailchimp-api-php

Let me know if you have any issues with that package; I'm new to using Packagist.

**Comment by taz77** [comment]
Awesome. Looks good!
