### ISSUE TITLE
Function for unscheduling a campaign

### ISSUE THREAD

**Issue by apmsooner** [thinkshout/mailchimp-api-php#41]
Can you consider adding this to the library please?

`/**
   * Unschedule a MailChimp campaign.
   *
   * @param string $campaign_id
   *   The ID of the campaign.
   * @return object
   *
   * @see http://developer.mailchimp.com/documentation/mailchimp/reference/campaigns/#action-post_campaigns_campaign_id_actions_unschedule
   */
  public function unschedule($campaign_id) {
    $tokens = [
      'campaign_id' => $campaign_id,
    ];

    return $this->request('POST', '/campaigns/{campaign_id}/actions/unschedule', $tokens, NULL);
  }`

**Comment by ruscoe** [comment]
Done: https://github.com/thinkshout/mailchimp-api-php/commit/e73f6154c18da2e67a3d5b47863be24b61cbbd1a
