### ISSUE TITLE
Campaign Send checklist function

### ISSUE THREAD

**Issue by apmsooner** [thinkshout/mailchimp-api-php#42]
Thanks for adding all the features i've been asking for. Here's another one that is actually pretty important. The reason this one is helpful is to determine whether the campaign is actually ready to send prior to sending it. The api documentation will return an is_ready value as well as a summary list of issues if any. In some cases on our end, we have tried to send a campaign that either did not have any subscribers to send to or the from_email for the campaign was using a domain that had not been verified. The latter is an issue recurring issue for us as we manage campaigns for our clients that have their own email as the from email so the email domain needs to be verified or else mailchimp won't allow the campaign to send. I believe this would be the case for scheduled campaigns as well.

`/**
   * Get the send checklist for a MailChimp campaign.
   *
   * @param string $campaign_id
   *   The ID of the campaign.
   * @return object
   *
   * @see http://developer.mailchimp.com/documentation/mailchimp/reference/campaigns/send-checklist
   */
  public function send_checklist($campaign_id) {
    $tokens = [
      'campaign_id' => $campaign_id,
    ];

    return $this->request('GET', '/campaigns/{campaign_id}/send-checklist', $tokens, NULL);
  }`

**Comment by ruscoe** [comment]
Added: https://github.com/thinkshout/mailchimp-api-php/commit/49899bf6c708df3391815b247d7193e1b8e8862b

I renamed the function to `getSendChecklist` just for consistency with the library. Everything else looks good.
