### ISSUE TITLE
Schedule Campaign variables

### ISSUE THREAD

**Issue by apmsooner** [thinkshout/mailchimp-api-php#44]
$timewarp & $batch_delivery should have default values i think...

public function schedule($campaign_id, $schedule_time, $timewarp = FALSE, $batch_delivery = FALSE, $parameters = [], $batch = FALSE) {
    $tokens = [
      'campaign_id' => $campaign_id,
    ];

    $parameters += [
      'schedule_time' => $schedule_time,
      'timewarp' => $timewarp,
      'batch_delivery' => $batch_delivery,
    ];

    return $this->request('POST', '/campaigns/{campaign_id}/actions/schedule', $tokens, $parameters, $batch);
  }

**Comment by ruscoe** [comment]
You're correct! Thanks for catching that.
