### ISSUE TITLE
MailchimpCURLClient response check is wrong with campaign

### ISSUE THREAD

**Issue by Besfr** [thinkshout/mailchimp-api-php#46]
Using Drupal 7 + mailchimp module 7.x-4.7 in a 5.4.45 PHP environment.

Once you fix all the composer and module php 5.5 requirement stuff you can install and use.

But creating a campaign in Drupal result in nothing except this notice
Notice : Undefined property: stdClass::$detail dans Mailchimp\MailchimpCURLClient->request() (ligne 98 dans /data/guillaume/git/avise-13-001/drupal/sites/all/libraries/mailchimp/src/MailchimpCURLClient.php).

Looking around this code i found this comment https://github.com/thinkshout/mailchimp-api-php/commit/a1a6a9fcad8e8e30be42df4597d9c407e96a6080

The problem seems to be that the response of a campaign creation contains a status (send, saved, etc) which is not what we want to test here. And so all the rest is stopped because of the exception.

**Comment by Besfr** [comment]
I push #48 that seems to works for me.

**Comment by ruscoe** [comment]
Thank you for the pull request. It worked perfectly.
