### ISSUE TITLE
Handle MailChimp exception classes with cURL

### ISSUE THREAD

**Issue by mshaver** [thinkshout/mailchimp-api-php#50]
There are a few places where MailChimp error exceptions are not being handled by cURL because we expect them to be handled with Guzzle. We need to update MailchimpLists.php and Mailchimp.php to handle these. 

`throw new MailchimpAPIException($e->getResponse()`

to this:

`throw new MailchimpAPIException($e->getMessage()`

**Comment by ruscoe** [comment]
https://github.com/thinkshout/mailchimp-api-php/commit/79b38c5af3f31a6c768b9b3779610a84b880d37b
