### ISSUE TITLE
Wrong version

### ISSUE THREAD

**Issue by apmsooner** [thinkshout/mailchimp-api-php#51]
Mailchimp.php still lists version 1.0.5

`const VERSION = '1.0.5';`

**Comment by kirkby** [comment]
And composer.json.

**Comment by MegaChriz** [comment]
This causes issues for installing the library through composer for the Drupal MailChimp module. See this bug report on drupal.org: https://www.drupal.org/node/2850362

**Comment by ruscoe** [comment]
Thanks for catching that. v1.0.6 has been updated with fixed version numbers: https://github.com/thinkshout/mailchimp-api-php/releases/tag/v1.0.6
