### ISSUE TITLE
Converting to short array syntax

### ISSUE THREAD

**Issue by taz77** [thinkshout/mailchimp-api-php#7]
Since this API requires Guzzle 6.x and hence requires PHP >= 5.4. Would there be any issues converting to the short array syntax? Makes for quicker coding and easier to read IMHO.

I will be glad to do it if you guys don't have a problem with it.

**Comment by ruscoe** [comment]
That would be great. Shot array syntax looks like it's becoming standard in newer PHP applications.

**Comment by taz77** [comment]
Ok will do. I will get this worked in as a PR once all the other stuff I did today finds a home.
