### ISSUE TITLE
Mailchimp API responses lack body with HTTP/1.1

### ISSUE THREAD

**Issue by idmacdonald** [thinkshout/mailchimp-api-php#73]
Hi,

As reported in the Drupal Mailchimp issue queue, it appears that HTTP/1.1 queries to the Mailchimp API produce, under some circumstances, a response with an empty body.

The solution seems to be to force the library to use HTTP/1.0 for Mailchimp API calls.

Here is the report within the Drupal issue queue:
https://www.drupal.org/project/mailchimp/issues/2825936

**Comment by aprice42** [comment]
The original issue on D.O was postponed, going to close this since it is quite old. Please reopen if you feel it is still required.
