### ISSUE TITLE
Proxy support to v2 for PHP 5.4  

### ISSUE THREAD

**Issue by Tamarpe** [thinkshout/mailchimp-api-php#85]
On PHP 5.4, the cURL HHTP client is in use, and it doesn't support proxy.
The support for proxy is only with Guzzle client.

https://github.com/thinkshout/mailchimp-api-php/blob/v2.0.0/src/Mailchimp.php#L334

```
    // Use cURL HTTP client if PHP version is below 5.5.0.
    // Use Guzzle client otherwise.
    if (version_compare(phpversion(), '5.5.0', '<')) {
      $client = new MailchimpCurlHttpClient($http_options);
    }
    else {
      $client = new MailchimpGuzzleHttpClient($http_options);
    }

```

**Comment by Tamarpe** [comment]
Added a pull request - https://github.com/thinkshout/mailchimp-api-php/pull/86/files

**Comment by mortenson** [comment]
PR has been merged.
