### ISSUE TITLE
Release with dependencies.

### ISSUE THREAD

**Issue by jsayegh** [thinkshout/mailchimp-api-php#92]
Hello, 

I saw that in [the following release](https://github.com/thinkshout/mailchimp-api-php/releases/tag/v1.0.9) you are providing a link to the library files[ with the dependencies](https://github.com/thinkshout/mailchimp-api-php/files/1489070/v1.0.9-package.zip) included. I just wanted to know how did you get this url. Was this link generated when you created the release ? Or were they uploaded directly in the repository? 

I would like to get a similar link for another php library, since it's very helpful. I'm using drush to create platforms on aegir to deploy a drupal website and this url you provided is helpful since i won't have to install the dependencies manually using composer and it would save a lot of time for each platform i create. 

So i would like to know how did you get this url. 

Thanks in advance.

**Comment by ruscoe** [comment]
It's done manually. GitHub allows us to attach files to releases.

For this repo, we just ran composer manually, zipped up the whole package, then uploaded it as part of the release.

**Comment by jsayegh** [comment]
@ruscoe thought so. Thank you so much for your answer..
