### ISSUE TITLE
Tag release 2.1.0

### ISSUE THREAD

**Issue by anthonyrw** [thinkshout/mailchimp-api-php#93]
Since the 2.0.0, functions and tests for Member Tags, Promo Rules/Codes, Interest Groups, and more have been committed. Can we tag a new release?

**Comment by ar-jan** [comment]
And hopefully also address #71, because when using drush users are now limited to using the outdated v1.

**Comment by mariacha** [comment]
Done: https://github.com/thinkshout/mailchimp-api-php/releases/tag/v2.1.0
